#
# Makefile for misc devices that really don't fit anywhere else.
#
ifeq ($(CONFIG_MTK_CAM_PD2085), y)
#obj-y += ois_dw9781c.o
endif
ifeq ($(CONFIG_MTK_CAM_PD2072), y)
obj-y += ois_dw9781c.o
endif
ifeq ($(CONFIG_MTK_CAM_PD2083F_EX), y)
obj-y += ois_dw9781c.o
endif