obj-y += vivo_board_info.o
vivo_board_info-y := bbk_board_info.o

obj-y += vivo_board_info_detect.o
vivo_board_info_detect-y := bbk_driver_common.o \
                            bbk_board_verison.o \
                            bbk_card_detect.o

